### ISSUE TITLE
Multiplayer doesn't work

### ISSUE THREAD

**Issue by simbaa345** [Lab-Jumpers/Lab-Jumpers#1]
**Platform and Version**
Platform: Windows, Mac or Linux
Version: Game version number

**Describe the bug**

**To Reproduce**
1. Go to...
2. Click on...
3. Scroll down to...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Alex25820** [comment]
I am now closing this issue due to a lack of information since you have failed to fill out the bug report.
